name: Build Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  docker:
    strategy:
      matrix:
        UBUNTU_VERSION: [20.04, 22.04, 18.04]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ matrix.UBUNTU_VERSION == '22.04' && 'fripside2021/my-dev:latest' || '' }}
            fripside2021/my-dev:${{ matrix.UBUNTU_VERSION }}
          build-args: UBUNTU_VERSION=${{ matrix.UBUNTU_VERSION }}
      #-
      #  name: Update repo description
      #  uses: peter-evans/dockerhub-description@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_PASSWORD }}
      #    repository: nyamisty/dev
